feat: When checking board_spec patches missing, make will be halted Now  #SDK-17778
*none

Change-Id: I664feb5a45c1c608b5215a938ace5e694e845497
Signed-off-by: chenyk <yongkang.chen@gl-inet.com>

diff --git a/kmod-amneziawg/Makefile b/kmod-amneziawg/Makefile
--- a/kmod-amneziawg/Makefile
+++ b/kmod-amneziawg/Makefile
@@ -62,10 +62,14 @@ ifneq ($(WG_IN_TREE_DIR),)
 			[ -f "$$$$patch" ] && echo "Applying $$$$patch" && patch -d $(PKG_BUILD_DIR) -F3 -t -p0 < "$$$$patch" || true; \
 		done; \
 	fi
-	- if [ -d "$(CURDIR)/board_spec/$(BOARD)/$(SUBTARGET)/patches" ]; then \
+	if [ -d "$(CURDIR)/board_spec/$(BOARD)/$(SUBTARGET)/patches" ]; then \
 		for patch in $(CURDIR)/board_spec/$(BOARD)/$(SUBTARGET)/patches/*.patch; do \
 			[ -f "$$$$patch" ] && echo "Applying $$$$patch" && patch -d $(PKG_BUILD_DIR) -F3 -t -p0 < "$$$$patch" || true; \
 		done; \
+	else \
+		echo "[amneziawg-InTree] ERROR: No board-specific patches found for $(BOARD)/$(SUBTARGET) in-tree build!"; \
+		exit 1; \
+	fi
 	fi
 	$(CP) -v $(CURDIR)/src/Makefile $(PKG_BUILD_DIR)
 else
